# File: .github/workflows/setup-node/action.yml
name: build-and-upload
description: "Build next js project âš™ï¸ - Upload ./out as artifact âš¡"
runs:
  using: "composite"
  steps:
    - name: Setup Pages âš™ï¸
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next

    - name: Build with Next.js ğŸ—ï¸
      shell: bash
      run: npm run build

    - name: Show stuff
      shell: bash
      run: ls -lah

    - name: Upload artifact ğŸ“¡
      uses: actions/upload-pages-artifact@v3
      with:
        path: out
